// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbiarchxbeznfwyvbqzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNiaWFyY2h4YmV6bmZ3eXZicXpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA4ODc3NzEsImV4cCI6MjA0NjQ2Mzc3MX0.7UIl7IDDecp17X1ijHp6KBc9wm51NifBh3Yvyzu5Wjs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);